export const authConstant = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
};

export const userConstant = {
  GET_USERLIST: "GET_USERLIST",
  GET_CONVERSATIONS: "GET_CONVERSATIONS",
  FILTER_CONVERSATIONS: "FILTER_CONVERSATIONS",
  START_CONVERSATION: "START_CONVERSATION",
  REFRESH_STATE: "REFRESH_STATE",
};
